Multisig permission
OpenNetworking/gcoin-community pull request #108
Opened 2016-11-09 08:54 UTC by lbyyy

#96

- Only 1 VOTE type coin as alliance token which store in multi-sig of alliance member
  - Transfer of this token means change of alliance member
- Alliance list record pubkey not address
- A new consensus address for license usage (multi-sig address by all alliance)
- Admin coin must mint to consensus address and dont need to sign signature and only use to issue new license
- License issueing must send from consensus address

2016-11-16 10:27 UTC, hihiben requested changes
Review到CWallet::CreateLicense

2016-11-16 10:27 UTC, hihiben commented on src/init.cpp
> +    if (mapArgs.count("-alliance") && mapArgs.count("-miner") && mapMultiArgs["-alliance"].size() > 0) {
應該不用`&& mapMultiArgs["-alliance"].size() > 0`

2016-11-16 10:27 UTC, hihiben commented on src/coins.h
> +#include <boost/tuple/tuple.hpp>
tuple還有用到嗎？

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +        } else if (addr != ConsensusAddressForLicense) {
`&& ConsensusAddressForMiner` ?

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +        if (pblock && (*pblock).GetHash() == consensusParams.hashGenesisBlock) {
可以直接放進condition裡面就好了

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +            GenerateGcoins(false, pwalletMain, 0);
需要加入
`mapArgs["-gen"] = "0";`
`mapArgs ["-genproclimit"] = "0";`

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +                if (coins->IsCoinBase() && tx.type != VOTE) {
如果是License轉移，前一筆會是LICENSE這樣要check嗎？

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +            } else if (tx.vout[0].color != DEFAULT_ADMIN_COLOR) {
admin color的沒有signature的話tx會長得一模一樣

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +                CoinBaseCount--;
跳過nValue為0的coinbase transaction時會不會造成下面利用CoinBaseCount來定位的判斷出錯？

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +        BOOST_FOREACH(const CTxOut &txout, tx.vout) {
同前面的，這個check可能要想一下

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> +
：）

2016-11-16 10:27 UTC, hihiben commented on src/main.cpp
> -
：）

2016-11-16 10:27 UTC, hihiben commented on src/rpcnet.cpp
> +    obj.push_back(Pair("Consensus address for license", ConsensusAddressForLicense));
for miner的也push一下？

2016-11-16 10:27 UTC, hihiben commented on src/txmempool.cpp
> +bool CCoinsViewMemPool::GetAddrCoins(const string &addr, CAddrTxOutMap &mapTxOut) const
這個function有修，要改一下

2016-11-16 10:27 UTC, hihiben commented on src/wallet/rpcwallet.cpp
> +Value mintforminer(const Array& params, bool fHelp)
mintlicense和mintforminer兩個命名統一一下吧

2016-11-16 10:27 UTC, hihiben commented on src/wallet/rpcwallet.cpp
> +        throw JSONRPCError(RPC_INVALID_PARAMETER, string("Please use mintlicense for DEFAULT_ADMIN_COLOR coin"));
也有可能是mintforminer?

2016-11-16 10:27 UTC, hihiben commented on src/wallet/wallet.cpp
> +        address = CBitcoinAddress(ConsensusAddressForLicense);
ForLicense和ForMiner怎麼區分？

2016-11-17 03:56 UTC, lbyyy commented on src/main.cpp
> +                if (coins->IsCoinBase() && tx.type != VOTE) {
這個與此次PR關係不大  應另開issue解決

2016-11-17 05:15 UTC, lbyyy commented on src/txmempool.cpp
> +bool CCoinsViewMemPool::GetAddrCoins(const string &addr, CAddrTxOutMap &mapTxOut) const
仔細想這個case中應該不會有mempool的case
畢竟都要等maturity

2016-11-17 05:41 UTC, hihiben commented on src/wallet/wallet.cpp
> +bool CWallet::CreateLicense(const CTxDestination &address, const type_Color color, const string &info, CWalletTx& wtxNew)
`CreateLicense` `SetMiner` `SetAlliance`應該都可以移出Wallet，看看要不要之後另外開一個改`CommitTransaction`的來改好了。

2016-11-17 06:52 UTC, lbyyy commented on src/main.cpp
> +            } else if (tx.vout[0].color != DEFAULT_ADMIN_COLOR) {
done

2016-11-18 05:43 UTC, hihiben requested changes

2016-11-18 05:43 UTC, hihiben commented on src/wallet/wallet.cpp
> +uint256 txHASH;
Remove?

2016-11-21 08:12 UTC, hihiben approved these changes

2016-11-21 08:18 UTC, merged