Fix error when number of allliance only 1
OpenNetworking/gcoin-community pull request #119
Opened 2016-12-05 12:11 UTC by lbyyy

Cause : (int)( 1 * 0.5) = 0

2016-12-06 06:22 UTC, hihiben requested changes

2016-12-06 06:22 UTC, hihiben commented on src/init.cpp
> +            CScript licenseaddr = _createmultisig_redeemScript(max(1, (int)(palliance->NumOfMembers() * Params().LicenseThreshold())), key);
是不是應該直接+1啊？

2016-12-06 10:45 UTC, lbyyy commented on src/init.cpp
> +            CScript licenseaddr = _createmultisig_redeemScript(max(1, (int)(palliance->NumOfMembers() * Params().LicenseThreshold())), key);
只有0的case需要改成1吧

2016-12-07 07:56 UTC, hihiben commented on src/init.cpp
> +            CScript licenseaddr = _createmultisig_redeemScript(max(1, (int)(palliance->NumOfMembers() * Params().LicenseThreshold())), key);
ceil?

2016-12-08 06:52 UTC, closed without merging