Multisiglimit
OpenNetworking/gcoin-community pull request #125
Opened 2016-12-28 08:25 UTC by lbyyy

as #116 

目前調整後理論上應該可支援到100-of-100的multi-sig transaction
(實測只測到50左右)

2016-12-30 08:57 UTC, lbyyy commented
補充一下  那個unit test是因為原本只支援 x of 3
現在不用  就可以拿掉 1 of 4 check了

2017-01-03 02:58 UTC, hihiben requested changes

2017-01-03 02:58 UTC, hihiben commented on src/script/interpreter.cpp
> +                    if (nKeysCount < 0 )
現在沒有上限了嗎？

2017-01-03 02:58 UTC, hihiben commented on src/script/script.cpp
> -    if (keys.size() > 16)
上限是上修還是移除啊？

2017-01-03 02:58 UTC, hihiben commented on src/script/standard.cpp
> -
沒事別移？

2017-01-03 02:58 UTC, hihiben commented on src/script/standard.cpp
> +    if (!Solver(scriptPubKey, whichType, vSolutions)) {
沒事別加？

2017-01-03 02:58 UTC, hihiben commented on src/script/standard.cpp
> +        if (n < 1)
同樣，上限是移除還是調整？

2017-01-03 06:49 UTC, lbyyy commented
我上限先改到100好了 size是用100-of-100去估的

2017-01-03 06:59 UTC, lbyyy commented
done

2017-01-03 09:57 UTC, hihiben approved these changes

2017-01-04 08:22 UTC, merged